#!/usr/bin/env node
/**
 * Static icon registry guard.
 *
 * NG-ZORRO icons are registered statically (see src/app/core/icons/demo-icons.ts) so the
 * build does not ship 800+ SVG files nor fetch them at runtime. This script scans every
 * string literal in src/ that matches an Ant Design icon name and compares the result with
 * the registry.
 *
 *   node scripts/check-icons.mjs          → exit 1 if an icon used in src/ is not registered
 *   node scripts/check-icons.mjs --write  → regenerate src/app/core/icons/demo-icons.ts
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const SRC = join(ROOT, 'src');
const REGISTRY = join(SRC, 'app', 'core', 'icons', 'demo-icons.ts');
const MANIFEST = join(
  ROOT,
  'node_modules',
  '@ant-design',
  'icons-angular',
  'types',
  'ant-design-icons-angular-icons.d.ts'
);

/** Strings that look like icon names but are used for something else in this codebase. */
const IGNORE = new Set([
  'default', 'primary', 'dashed', 'text', 'link', // nz-button types
  'error', 'success', 'warning', 'info', // nz-alert / nz-result statuses (icons are ng-zorro internals)
  'small', 'large', 'middle', 'left', 'right', 'top', 'bottom', 'center',
  'file', 'user', 'users', 'grid', 'shield', 'clock', 'activity', // inline SVG names of the palette/dashboard
  'menu', 'table', 'tag', 'tags', 'form', 'select', 'switch', 'number', 'block', 'border',
  'search', 'filter', 'edit', 'delete', 'save', 'close', 'check', 'plus', 'minus', 'upload', 'download',
  'mail', 'send', 'inbox', 'lock', 'unlock', 'setting', 'setting-filled', 'star', 'sync', 'reload', 'scan',
]);
// Names in IGNORE are still included when they appear as an explicit `nzType="..."`.

const ICON_LITERAL = /['"`]([a-z][a-z0-9]*(?:-[a-z0-9]+)*)['"`]/g;
const NZ_TYPE = /nzType\s*=\s*"([a-z][a-z0-9-]*)"|nzType\s*:\s*'([a-z][a-z0-9-]*)'|\[nzType\]\s*=\s*"[^"]*?'([a-z][a-z0-9-]*)'/g;
const NZ_THEME_FILL = /nzType="([a-z0-9-]+)"[^>]*nzTheme="fill"/g;

function walk(dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (/\.(ts|html)$/.test(entry) && !entry.endsWith('.spec.ts') && p !== REGISTRY) acc.push(p);
  }
  return acc;
}

const pascal = (kebab) => kebab.split('-').map((s) => s[0].toUpperCase() + s.slice(1)).join('');

// 1. Available icons from the package manifest
const manifest = readFileSync(MANIFEST, 'utf8');
const available = new Set([...manifest.matchAll(/declare const ([A-Za-z0-9]+(?:Outline|Fill|TwoTone)): IconDefinition/g)].map((m) => m[1]));
const outlineNames = new Set(); // kebab names that have an Outline variant
for (const id of available) if (id.endsWith('Outline')) outlineNames.add(id.slice(0, -'Outline'.length));

// 2. Icons used in src/
const used = new Map(); // identifier → first file
const files = walk(SRC);
for (const file of files) {
  const text = readFileSync(file, 'utf8');
  const rel = relative(ROOT, file);
  const add = (id) => { if (available.has(id) && !used.has(id)) used.set(id, rel); };

  for (const m of text.matchAll(NZ_TYPE)) add(`${pascal(m[1] ?? m[2] ?? m[3])}Outline`);
  for (const m of text.matchAll(NZ_THEME_FILL)) add(`${pascal(m[1])}Fill`);
  for (const m of text.matchAll(ICON_LITERAL)) {
    const name = m[1];
    if (IGNORE.has(name)) continue;
    const id = `${pascal(name)}Outline`;
    if (outlineNames.has(pascal(name))) add(id);
  }
}
// ng-zorro form/table internals always needed by the app shell
for (const id of ['LoadingOutline', 'DownOutline', 'UpOutline', 'CloseOutline', 'CheckOutline', 'SearchOutline', 'PlusOutline', 'DeleteOutline', 'EditOutline', 'SaveOutline', 'CloseCircleOutline', 'CheckCircleOutline', 'InfoCircleOutline', 'ExclamationCircleOutline', 'MinusCircleOutline', 'LeftOutline', 'RightOutline', 'EyeOutline', 'EyeInvisibleOutline', 'UserOutline', 'LockOutline', 'MailOutline', 'SendOutline', 'InboxOutline', 'FilterOutline', 'ReloadOutline', 'SyncOutline', 'UploadOutline', 'DownloadOutline', 'SettingOutline', 'TableOutline', 'TagOutline', 'TagsOutline', 'StarOutline', 'ScanOutline', 'QuestionCircleOutline', 'MenuFoldOutline', 'MenuUnfoldOutline', 'CalendarOutline', 'ClockCircleOutline', 'FileOutline', 'NumberOutline', 'FormOutline', 'BellOutline', 'LogoutOutline', 'DashboardOutline', 'TeamOutline', 'BankOutline', 'ShareAltOutline', 'ApartmentOutline', 'SwapOutline']) {
  if (available.has(id) && !used.has(id)) used.set(id, '(shell)');
}

const ids = [...used.keys()].sort();

if (process.argv.includes('--write')) {
  const body = `// Generated by \`npm run check:icons -- --write\` — do not edit by hand.
// Every NG-ZORRO icon used by the app, registered statically via provideNzIcons().
import type { IconDefinition } from '@ant-design/icons-angular';
import {
${ids.map((id) => `  ${id},`).join('\n')}
} from '@ant-design/icons-angular/icons';

export const DEMO_ICONS: IconDefinition[] = [
${ids.map((id) => `  ${id},`).join('\n')}
];
`;
  writeFileSync(REGISTRY, body);
  console.log(`✔ ${ids.length} icons written to ${relative(ROOT, REGISTRY)}`);
  process.exit(0);
}

// 3. Compare with the registry
let registry = '';
try { registry = readFileSync(REGISTRY, 'utf8'); } catch { /* missing */ }
const registered = new Set([...registry.matchAll(/^\s+([A-Za-z0-9]+(?:Outline|Fill|TwoTone)),$/gm)].map((m) => m[1]));
const missing = ids.filter((id) => !registered.has(id));
if (missing.length) {
  console.error(`✖ ${missing.length} icon(s) used in src/ but not registered:`);
  for (const id of missing) console.error(`   ${id}  (${used.get(id)})`);
  console.error('Run: node scripts/check-icons.mjs --write');
  process.exit(1);
}
console.log(`✔ ${registered.size} registered icons cover all ${ids.length} used in src/`);
